const defaultPlan = {
    "name": "New Plan",
    "scenario": "Status Quo",
    "color": "#555",
    "plan_type": "PPO",
    "tiers": [
        {
            "name": "In-Network",
            "discount_percent": 0.8,
            "utilization_percent": 0.8,
            "ind_ded": 1000,
            "fam_ded": 2000,
            "ind_oopm": 4000,
            "fam_oopm": 8000,
            "ded_type_family": false,
            "oopm_type_family": false,
            "fam_embd_ind_ded": -1,
            "fam_embd_ind_oopm": -1,
            "rx_ind_ded": -1,
            "rx_fam_ded": -1,
            "rx_ind_oopm": -1,
            "rx_fam_oopm": -1,
            "rx_embd_ind_ded": -1,
            "rx_embd_ind_oopm": -1,
            "coinsurance": 0.8,
            "service_cost_sharing": {
                "Prev": {"Copay": 0, "Coins": -1, "PerDiem": false},
            }
        },
        {

            "name": "Out-of-Network",
            "discount_percent": 0.0,
            "utilization_percent": 0.05,
            "ind_ded": 4000,
            "fam_ded": 8000,
            "ind_oopm": 8000,
            "fam_oopm": 16000,
            "family_ded_oopm": false,
            "fam_embd_ind_ded": -1,
            "fam_embd_ind_oopm": -1,
            "rx_ind_ded": -1,
            "rx_fam_ded": -1,
            "rx_ind_oopm": -1,
            "rx_fam_oopm": -1,
            "rx_embd_ind_ded": -1,
            "rx_embd_ind_oopm": -1,
            "coinsurance": 0.5,
        }
    ],
    "hsa_seed_ind": 0,
    "hsa_seed_fam": 0,
    "hra_fund_ind": 0,
    "hra_fund_fam": 0,
    "hra_first_dollar": false,
    "hra_forfeiture_pct": 0,
    "av_paid_amt": 0,
    "av_allowed_amt": 0,
    "av": 0,
    "av_hash": "",
    "av_version": "0",
}

export default defaultPlan;